<svelte:head>
  <title>Terms of Service — SOPHIA</title>
  <meta name="description" content="Terms of service for SOPHIA, the philosophical reasoning engine by Allotment Technology Ltd." />
</svelte:head>

<div class="legal-page">
  <header class="legal-header">
    <a href="/" class="back-link">← Back to SOPHIA</a>
    <h1>Terms of Service</h1>
    <p class="meta">Allotment Technology Ltd · Last updated: 9 March 2026</p>
  </header>

  <div class="legal-body">

    <section>
      <h2>1. Agreement</h2>
      <p>
        By creating an account or using SOPHIA, you agree to these Terms of Service. If you do not
        agree, do not use the service.
      </p>
      <p>
        SOPHIA is operated by <strong>Allotment Technology Ltd</strong>, a company registered in
        England and Wales. Contact: <a href="mailto:admin@usesophia.app">admin@usesophia.app</a>.
      </p>
    </section>

    <section>
      <h2>2. Description of service</h2>
      <p>
        SOPHIA is a structured philosophical reasoning engine. It uses a dialectical three-pass
        architecture — Analysis, Critique, and Synthesis — backed by a curated philosophical
        knowledge graph to produce reasoned responses to philosophical questions.
      </p>
      <p>
        SOPHIA is a research prototype. Outputs are intended to support philosophical inquiry and
        should not be treated as professional advice (legal, medical, financial, or otherwise).
      </p>
    </section>

    <section>
      <h2>3. Eligibility</h2>
      <p>
        You must be at least 18 years old to use SOPHIA. By signing in, you confirm you meet this
        requirement. We reserve the right to terminate accounts where this requirement is not met.
      </p>
    </section>

    <section>
      <h2>4. Your account</h2>
      <p>
        You sign in using Google via Firebase Authentication. You are responsible for maintaining
        the security of your Google account. We are not liable for any loss or damage arising from
        unauthorised access to your account.
      </p>
    </section>

    <section>
      <h2>5. Acceptable use</h2>
      <p>You agree not to use SOPHIA to:</p>
      <ul>
        <li>Generate, distribute, or promote content that is illegal, harmful, or abusive</li>
        <li>Attempt to extract, replicate, or reverse-engineer the knowledge graph, prompts, or
          system architecture through automated means</li>
        <li>Circumvent rate limits, access controls, or authentication mechanisms</li>
        <li>Use the service in any way that violates applicable laws or regulations</li>
        <li>Submit queries that are designed to elicit harmful outputs or to manipulate the reasoning
          engine in bad faith</li>
      </ul>
      <p>
        We reserve the right to suspend or terminate access for any violation of these terms.
      </p>
    </section>

    <section>
      <h2>6. Rate limits</h2>
      <p>
        Free access is subject to a limit of 20 analyses per user per day. We reserve the right to
        adjust this limit at any time with reasonable notice.
      </p>
    </section>

    <section>
      <h2>7. Intellectual property</h2>
      <p>
        The SOPHIA application, including its source code, prompt architecture, reasoning engine,
        and design system, is published under the MIT licence. The curated philosophical knowledge
        base is derived from copyrighted sources and is not redistributed.
      </p>
      <p>
        Queries you submit are your own content. By submitting a query, you grant Allotment
        Technology Ltd a limited, non-exclusive licence to process and store that query for the
        purpose of providing the service, including caching and history features.
      </p>
    </section>

    <section>
      <h2>8. Disclaimers</h2>
      <p>
        SOPHIA is provided "as is" without warranty of any kind. We do not warrant that:
      </p>
      <ul>
        <li>The service will be uninterrupted, error-free, or available at all times</li>
        <li>Outputs will be accurate, complete, or suitable for any particular purpose</li>
        <li>The knowledge graph is free from errors, omissions, or bias</li>
      </ul>
      <p>
        Outputs generated by SOPHIA are the product of language models and a structured knowledge
        graph. They reflect the positions of the sources ingested, the design of the prompts, and
        the limitations of current AI systems. They should be read critically, not as authoritative
        philosophical verdicts.
      </p>
    </section>

    <section>
      <h2>9. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, Allotment Technology Ltd shall not be liable for any
        indirect, incidental, special, consequential, or punitive damages arising from your use of
        SOPHIA, including but not limited to loss of data, loss of profits, or decisions made in
        reliance on SOPHIA outputs.
      </p>
      <p>
        Our total liability to you for any claim arising from these terms or your use of the service
        shall not exceed the amount you have paid to us in the 12 months preceding the claim (or
        £50 if you have paid nothing).
      </p>
    </section>

    <section>
      <h2>10. Termination</h2>
      <p>
        You may stop using SOPHIA at any time. We may suspend or terminate your access at any time
        if you violate these terms, or for operational reasons, with or without notice.
      </p>
    </section>

    <section>
      <h2>11. Changes to these terms</h2>
      <p>
        We may update these terms as the service evolves. We will notify you of material changes via
        the email address associated with your account. Continued use of SOPHIA after the effective
        date of a change constitutes acceptance of the updated terms.
      </p>
    </section>

    <section>
      <h2>12. Governing law</h2>
      <p>
        These terms are governed by the laws of England and Wales. Any disputes shall be subject to
        the exclusive jurisdiction of the courts of England and Wales.
      </p>
    </section>

    <section>
      <h2>13. Contact</h2>
      <p>
        Allotment Technology Ltd<br />
        <a href="mailto:admin@usesophia.app">admin@usesophia.app</a>
      </p>
    </section>

  </div>
</div>

<style>
  .legal-page {
    max-width: 720px;
    margin: 0 auto;
    padding: 3rem 1.5rem 5rem;
    color: var(--color-text);
    font-family: var(--font-ui);
  }

  .legal-header {
    margin-bottom: 3rem;
  }

  .back-link {
    display: inline-block;
    color: var(--color-muted);
    text-decoration: none;
    font-size: 0.875rem;
    margin-bottom: 1.5rem;
  }

  .back-link:hover {
    color: var(--color-text);
  }

  h1 {
    font-family: var(--font-display);
    font-size: 2.25rem;
    font-weight: 400;
    margin: 0 0 0.5rem;
    color: var(--color-text);
  }

  .meta {
    color: var(--color-muted);
    font-size: 0.875rem;
    margin: 0;
  }

  .legal-body section {
    margin-bottom: 2.5rem;
    border-top: 1px solid var(--color-dim);
    padding-top: 1.5rem;
  }

  h2 {
    font-family: var(--font-display);
    font-size: 1.25rem;
    font-weight: 400;
    margin: 0 0 1rem;
    color: var(--color-text);
  }

  p {
    font-size: 0.9375rem;
    line-height: 1.7;
    color: var(--color-text);
    margin: 0 0 0.75rem;
  }

  ul {
    margin: 0.5rem 0 0.75rem 1.25rem;
    padding: 0;
  }

  li {
    font-size: 0.9375rem;
    line-height: 1.7;
    margin-bottom: 0.25rem;
    color: var(--color-text);
  }

  a {
    color: var(--color-blue);
    text-decoration: underline;
    text-underline-offset: 2px;
  }
</style>
